export const initialState = {
  beerbiceps: {
    userID: "beerbiceps",
    profilePic:
      "https://i.pinimg.com/originals/08/1b/f6/081bf6e08af1bc9b7b8c67835842f947.jpg",
    followers: "7M",
    following: 200,
    name: "Ben Smith",
    category: "Entrepneure",
    bio: "Founder of Beer💪🏼 and busy building 5000 startups..",
    verified: true,
  },
  rohitdhas_11: {
    userID: "rohitdhas_11",
    profilePic: "https://avatars.githubusercontent.com/u/53969450?v=4",
    followers: "7.6B",
    following: 200,
    name: "Rohit Dhas",
    category: "Programmer",
    bio: "I Write Code👨🏼‍💻",
    verified: true,
  },
  carryminati: {
    userID: "carryminati",
    profilePic:
      "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80",
    followers: "12M",
    following: 750,
    name: "Andrew Nagar",
    category: "Youthober",
    bio: "Co-founder of Monk-E",
    verified: true,
  },
  viraj_seth: {
    userID: "viraj_seth",
    profilePic:
      "https://monk-e.in/assets/images/Our-Team/02%20Viraj%20Color.jpg",
    followers: "432k",
    following: 232,
    name: "Viraj Seth",
    category: "Entrepneure",
    bio: "Co-founder of Monk-E!",
    verified: true,
  },
  "mangesh.07": {
    userID: "mangesh.07",
    profilePic:
      "https://icon-library.com/images/no-profile-pic-icon/no-profile-pic-icon-24.jpg",
    followers: "44M",
    following: 1,
    name: "Mangesh Shinde",
    category: "Public Figure",
    bio: "Mahakal ka bhakt...🕉",
    verified: false,
  },
  Chris_Lin: {
    userID: "Chris_Lin",
    profilePic:
      "https://icon-library.com/images/no-profile-pic-icon/no-profile-pic-icon-24.jpg",
    followers: "21M",
    following: 131,
    name: "Chris Lin",
    category: "",
    bio: "😎Lucifer😎",
    verified: false,
  },
  kamlesh_sabale: {
    userID: "kamlesh_sabale_11",
    profilePic:
      "https://icon-library.com/images/no-profile-pic-icon/no-profile-pic-icon-24.jpg",
    followers: "12M",
    following: 159,
    name: "Kamlesh Sabale",
    category: "Fitness Model",
    bio: "👔Mr.Beast",
    verified: true,
  },
  silent_device: {
    userID: "silent_device",
    profilePic:
      "https://icon-library.com/images/no-profile-pic-icon/no-profile-pic-icon-24.jpg",
    followers: "18M",
    following: 795,
    name: "Vaibhav Dhas",
    category: "Artist",
    bio: "🅱🅸🆁🆃🅷🅳🅰🆈 🎂..... 12 🅳🅴🅲",
    verified: false,
  },
  sush_shinde11: {
    userID: "sush_shinde11",
    profilePic:
      "https://0.academia-photos.com/21801803/9307291/10374065/s200_sushma.shinde.jpg",
    followers: "4M",
    following: 345,
    name: "Sushma Shinde",
    category: "Software Engineer",
    bio: "Kaizen🤗",
    verified: true,
  },
  charlieputh: {
    userID: "charlieputh",
    profilePic:
      "https://static.wikia.nocookie.net/littlemix/images/b/b5/Charlie_puth_shoot.jpg/revision/latest/top-crop/width/360/height/450?cb=20180114181214",
    followers: "14M",
    following: 234,
    name: "Charlie Puth",
    category: "Artist",
    bio: "💡",
    verified: true,
  },
  justinbieber: {
    userID: "justinbieber",
    profilePic:
      "https://images.unsplash.com/flagged/photo-1570612861542-284f4c12e75f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80",
    followers: "177M",
    following: 534,
    name: "Justin Bieber",
    category: "Artist",
    bio: "JUSTICE the album out now",
    verified: true,
  },
  vivianakadivine: {
    userID: "vivianakadivine",
    profilePic:
      "https://images.unsplash.com/photo-1599566150163-29194dcaad36?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=987&q=80",
    followers: "3.4M",
    following: 534,
    name: "David",
    category: "Musician/Band",
    bio: "JUSTICE the album out now",
    verified: true,
  },
};
